// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 08_kehadiran_skp.sql

package pg

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveKehadiranSkpByIds = `-- name: ApproveKehadiranSkpByIds :exec
UPDATE public.kehadiran_skp ks
SET
  status = CASE
    WHEN ks.id = ANY($1::uuid[])
      THEN 'disetujui'
    ELSE 'ditolak'
  END,
  locked = TRUE,
  updated_at = now(),
  updated_by = $2
WHERE
  ks.kehadiran_id = $3::uuid
  AND ks.deleted_at IS NULL
  AND ks.is_active = TRUE
`

type ApproveKehadiranSkpByIdsParams struct {
	SkpKehadiranID []uuid.UUID `json:"skp_kehadiran_id"`
	UpdatedBy      *string     `json:"updated_by"`
	KehadiranID    uuid.UUID   `json:"kehadiran_id"`
}

func (q *Queries) ApproveKehadiranSkpByIds(ctx context.Context, arg ApproveKehadiranSkpByIdsParams) error {
	_, err := q.db.Exec(ctx, approveKehadiranSkpByIds, arg.SkpKehadiranID, arg.UpdatedBy, arg.KehadiranID)
	return err
}

const countKehadiranSkp = `-- name: CountKehadiranSkp :one
SELECT COUNT(*)::bigint
FROM kehadiran_skp
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status ILIKE '%' || $1 || '%')
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
  AND ($3::uuid IS NULL OR kehadiran_id = $3::uuid)
  AND ($4::uuid IS NULL OR skp_intervensi_id = $4::uuid)
`

type CountKehadiranSkpParams struct {
	Status          *string    `json:"status"`
	IsActive        *bool      `json:"is_active"`
	KehadiranID     *uuid.UUID `json:"kehadiran_id"`
	SkpIntervensiID *uuid.UUID `json:"skp_intervensi_id"`
}

func (q *Queries) CountKehadiranSkp(ctx context.Context, arg CountKehadiranSkpParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKehadiranSkp,
		arg.Status,
		arg.IsActive,
		arg.KehadiranID,
		arg.SkpIntervensiID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteKehadiranSkp = `-- name: DeleteKehadiranSkp :exec
UPDATE kehadiran_skp
SET deleted_at = now(),
    deleted_by = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type DeleteKehadiranSkpParams struct {
	ID        uuid.UUID `json:"id"`
	DeletedBy *string   `json:"deleted_by"`
}

func (q *Queries) DeleteKehadiranSkp(ctx context.Context, arg DeleteKehadiranSkpParams) error {
	_, err := q.db.Exec(ctx, deleteKehadiranSkp, arg.ID, arg.DeletedBy)
	return err
}

const getCapaianSKP7HariTerakhir = `-- name: GetCapaianSKP7HariTerakhir :many
WITH date_series AS (
  SELECT generate_series(
    ($1::date - INTERVAL '6 day'),
    $1::date,
    INTERVAL '1 day'
  )::date AS tanggal
),
rekap AS (
  SELECT
    k.tgl_kehadiran::date AS tanggal,
    COUNT(ks.id) AS total_skp,
    COUNT(*) FILTER (WHERE (ks.status = 'verified' OR ks.locked = TRUE)) AS diverifikasi,
    COUNT(*) FILTER (WHERE ks.status = 'rejected') AS ditolak,
    COUNT(*) FILTER (
      WHERE ks.status IS NULL OR ks.status NOT IN ('verified', 'rejected')
    ) AS belum_diverifikasi
  FROM kehadiran_skp ks
  JOIN kehadiran k ON k.id = ks.kehadiran_id
  WHERE ks.is_active = TRUE
    AND k.is_active = TRUE
    AND k.tgl_kehadiran BETWEEN ($1::date - INTERVAL '6 day') AND $1::date
  GROUP BY k.tgl_kehadiran
)
SELECT
  ds.tanggal,
  COALESCE(r.total_skp, 0) AS total_skp,
  COALESCE(r.diverifikasi, 0) AS diverifikasi,
  COALESCE(r.ditolak, 0) AS ditolak,
  COALESCE(r.belum_diverifikasi, 0) AS belum_diverifikasi,
  ROUND(
    (COALESCE(r.diverifikasi, 0)::numeric / NULLIF(r.total_skp, 0)) * 100,
    2
  ) AS persentase_diverifikasi
FROM date_series ds
LEFT JOIN rekap r ON r.tanggal = ds.tanggal
ORDER BY ds.tanggal ASC
`

type GetCapaianSKP7HariTerakhirRow struct {
	Tanggal                pgtype.Date    `json:"tanggal"`
	TotalSkp               int64          `json:"total_skp"`
	Diverifikasi           int64          `json:"diverifikasi"`
	Ditolak                int64          `json:"ditolak"`
	BelumDiverifikasi      int64          `json:"belum_diverifikasi"`
	PersentaseDiverifikasi pgtype.Numeric `json:"persentase_diverifikasi"`
}

func (q *Queries) GetCapaianSKP7HariTerakhir(ctx context.Context, tgl pgtype.Date) ([]GetCapaianSKP7HariTerakhirRow, error) {
	rows, err := q.db.Query(ctx, getCapaianSKP7HariTerakhir, tgl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCapaianSKP7HariTerakhirRow{}
	for rows.Next() {
		var i GetCapaianSKP7HariTerakhirRow
		if err := rows.Scan(
			&i.Tanggal,
			&i.TotalSkp,
			&i.Diverifikasi,
			&i.Ditolak,
			&i.BelumDiverifikasi,
			&i.PersentaseDiverifikasi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapaianSKPPerHari = `-- name: GetCapaianSKPPerHari :many
SELECT
  k.tgl_kehadiran::date AS tanggal,
  COUNT(ks.id) AS total_skp,
  COUNT(*) FILTER (WHERE (ks.status = 'disetujui' OR ks.locked = TRUE)) AS diverifikasi,
  COUNT(*) FILTER (WHERE ks.status = 'ditolak') AS ditolak,
  COUNT(*) FILTER (
    WHERE ks.status IS NULL OR ks.status NOT IN ('disetujui', 'ditolak')
  ) AS belum_diverifikasi,
  ROUND(
    (COUNT(*) FILTER (WHERE (ks.status = 'disetujui' OR ks.locked = TRUE))::numeric
      / NULLIF(COUNT(ks.id), 0)) * 100,
    2
  ) AS persentase_diverifikasi
FROM kehadiran_skp ks
JOIN kehadiran k ON k.id = ks.kehadiran_id
WHERE ks.is_active = TRUE
  AND k.is_active = TRUE
  AND k.tgl_kehadiran BETWEEN $1::date AND $2::date
GROUP BY k.tgl_kehadiran
ORDER BY k.tgl_kehadiran ASC
`

type GetCapaianSKPPerHariParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetCapaianSKPPerHariRow struct {
	Tanggal                pgtype.Date    `json:"tanggal"`
	TotalSkp               int64          `json:"total_skp"`
	Diverifikasi           int64          `json:"diverifikasi"`
	Ditolak                int64          `json:"ditolak"`
	BelumDiverifikasi      int64          `json:"belum_diverifikasi"`
	PersentaseDiverifikasi pgtype.Numeric `json:"persentase_diverifikasi"`
}

func (q *Queries) GetCapaianSKPPerHari(ctx context.Context, arg GetCapaianSKPPerHariParams) ([]GetCapaianSKPPerHariRow, error) {
	rows, err := q.db.Query(ctx, getCapaianSKPPerHari, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCapaianSKPPerHariRow{}
	for rows.Next() {
		var i GetCapaianSKPPerHariRow
		if err := rows.Scan(
			&i.Tanggal,
			&i.TotalSkp,
			&i.Diverifikasi,
			&i.Ditolak,
			&i.BelumDiverifikasi,
			&i.PersentaseDiverifikasi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalSKPPersentase = `-- name: GetGlobalSKPPersentase :many
WITH Total AS (
  SELECT COUNT(*) AS total
  FROM kehadiran_skp ks
  JOIN kehadiran k ON k.id = ks.kehadiran_id
  WHERE ks.is_active = TRUE
    AND k.is_active = TRUE
    AND k.tgl_kehadiran BETWEEN ($1::date - INTERVAL '6 day') AND $1::date
)
SELECT
  CASE
    WHEN (ks.status = 'verified' OR ks.locked = TRUE) THEN 'Diverifikasi'
    WHEN ks.status = 'rejected' THEN 'Ditolak'
    ELSE 'Belum Diverifikasi'
  END AS kategori,
  COUNT(*) AS jumlah,
  ROUND(
    (COUNT(*)::numeric / NULLIF(t.total, 0)) * 100,
    2
  ) AS persentase
FROM kehadiran_skp ks
JOIN kehadiran k ON k.id = ks.kehadiran_id
CROSS JOIN Total t
WHERE ks.is_active = TRUE
  AND k.is_active = TRUE
  AND k.tgl_kehadiran BETWEEN ($1::date - INTERVAL '6 day') AND $1::date
GROUP BY kategori, t.total
ORDER BY persentase DESC
`

type GetGlobalSKPPersentaseRow struct {
	Kategori   string         `json:"kategori"`
	Jumlah     int64          `json:"jumlah"`
	Persentase pgtype.Numeric `json:"persentase"`
}

func (q *Queries) GetGlobalSKPPersentase(ctx context.Context, tgl pgtype.Date) ([]GetGlobalSKPPersentaseRow, error) {
	rows, err := q.db.Query(ctx, getGlobalSKPPersentase, tgl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGlobalSKPPersentaseRow{}
	for rows.Next() {
		var i GetGlobalSKPPersentaseRow
		if err := rows.Scan(&i.Kategori, &i.Jumlah, &i.Persentase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalSKPPersentaseTahunanOtomatis = `-- name: GetGlobalSKPPersentaseTahunanOtomatis :many
WITH KategoriSemua AS (
    SELECT UNNEST(ARRAY['Tercapai', 'Belum Tercapai', 'Belum Diverifikasi']) AS kategori_nama
),
Total AS (
    SELECT COUNT(*) AS total
    FROM kehadiran_skp ks
    JOIN kehadiran k ON k.id = ks.kehadiran_id
    WHERE ks.is_active = TRUE
      AND k.is_active = TRUE
      AND k.tgl_kehadiran BETWEEN date_trunc('year', CURRENT_DATE)::date AND CURRENT_DATE
),
DataRekap AS (
    SELECT
        CASE
            WHEN (ks.status = 'disetujui' OR ks.locked = TRUE) THEN 'Tercapai'
            WHEN ks.status = 'ditolak' THEN 'Belum Tercapai'
            ELSE 'Belum Diverifikasi'
        END AS kategori_status,
        COUNT(*) AS jumlah
    FROM kehadiran_skp ks
    JOIN kehadiran k ON k.id = ks.kehadiran_id
    WHERE ks.is_active = TRUE
      AND k.is_active = TRUE
      AND k.tgl_kehadiran BETWEEN date_trunc('year', CURRENT_DATE)::date AND CURRENT_DATE
    GROUP BY kategori_status
)
SELECT
    ks.kategori_nama AS kategori,
    COALESCE(dr.jumlah, 0) AS jumlah,
    t.total AS total_skp,
    ROUND(
        (COALESCE(dr.jumlah, 0)::numeric / NULLIF(t.total, 0)) * 100,
        2
    ) AS persentase
FROM KategoriSemua ks
LEFT JOIN DataRekap dr ON dr.kategori_status = ks.kategori_nama
CROSS JOIN Total t
ORDER BY persentase DESC
`

type GetGlobalSKPPersentaseTahunanOtomatisRow struct {
	Kategori   interface{}    `json:"kategori"`
	Jumlah     int64          `json:"jumlah"`
	TotalSkp   int64          `json:"total_skp"`
	Persentase pgtype.Numeric `json:"persentase"`
}

func (q *Queries) GetGlobalSKPPersentaseTahunanOtomatis(ctx context.Context) ([]GetGlobalSKPPersentaseTahunanOtomatisRow, error) {
	rows, err := q.db.Query(ctx, getGlobalSKPPersentaseTahunanOtomatis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGlobalSKPPersentaseTahunanOtomatisRow{}
	for rows.Next() {
		var i GetGlobalSKPPersentaseTahunanOtomatisRow
		if err := rows.Scan(
			&i.Kategori,
			&i.Jumlah,
			&i.TotalSkp,
			&i.Persentase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKehadiranSkp = `-- name: GetKehadiranSkp :one
SELECT id, kehadiran_id, skp_intervensi_id, user_id, status, is_active, locked, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at
FROM kehadiran_skp
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetKehadiranSkp(ctx context.Context, id uuid.UUID) (KehadiranSkp, error) {
	row := q.db.QueryRow(ctx, getKehadiranSkp, id)
	var i KehadiranSkp
	err := row.Scan(
		&i.ID,
		&i.KehadiranID,
		&i.SkpIntervensiID,
		&i.UserID,
		&i.Status,
		&i.IsActive,
		&i.Locked,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.UpdatedNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRekapSKPHarian = `-- name: GetRekapSKPHarian :one
WITH DataSKP AS (
  SELECT
    COUNT(*) AS total_kompetensi,
    COUNT(*) FILTER (
      WHERE (ks.status = 'verified' OR ks.locked = TRUE)
    ) AS diverifikasi
  FROM kehadiran_skp ks
  JOIN kehadiran k ON k.id = ks.kehadiran_id
  WHERE k.tgl_kehadiran = $1
    AND ks.is_active = TRUE
    AND k.is_active = TRUE
)
SELECT
  COALESCE(ds.total_kompetensi, 0) AS total_kompetensi_dicatat,
  COALESCE(ds.diverifikasi, 0) AS sudah_diverifikasi_pembimbing,
  ROUND(
    (COALESCE(ds.diverifikasi, 0)::numeric / NULLIF(ds.total_kompetensi, 0)) * 100,
    2
  ) AS persentase_selesai
FROM DataSKP ds
`

type GetRekapSKPHarianRow struct {
	TotalKompetensiDicatat      int64          `json:"total_kompetensi_dicatat"`
	SudahDiverifikasiPembimbing int64          `json:"sudah_diverifikasi_pembimbing"`
	PersentaseSelesai           pgtype.Numeric `json:"persentase_selesai"`
}

func (q *Queries) GetRekapSKPHarian(ctx context.Context, tgl pgtype.Date) (GetRekapSKPHarianRow, error) {
	row := q.db.QueryRow(ctx, getRekapSKPHarian, tgl)
	var i GetRekapSKPHarianRow
	err := row.Scan(&i.TotalKompetensiDicatat, &i.SudahDiverifikasiPembimbing, &i.PersentaseSelesai)
	return i, err
}

const getRekapSkpTercapaiByUser = `-- name: GetRekapSkpTercapaiByUser :many
SELECT
  si.nama AS nama_skp,
  COUNT(ks.id) AS jumlah_tercapai,
  COALESCE(string_agg(DISTINCT to_char(k.tgl_kehadiran, 'DD-MM-YYYY'), ', '), '')::text AS tanggal_tercapai
FROM kehadiran_skp ks
JOIN kehadiran k ON k.id = ks.kehadiran_id
JOIN skp_intervensi si ON si.id = ks.skp_intervensi_id
WHERE
  ks.user_id = $1
  AND ks.status = 'disetujui'
  AND ks.is_active = TRUE
  AND k.is_active = TRUE
  AND k.tgl_kehadiran BETWEEN $2 AND $3
GROUP BY si.nama
ORDER BY si.nama ASC
`

type GetRekapSkpTercapaiByUserParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	TglAwal  pgtype.Date `json:"tgl_awal"`
	TglAkhir pgtype.Date `json:"tgl_akhir"`
}

type GetRekapSkpTercapaiByUserRow struct {
	NamaSkp         string `json:"nama_skp"`
	JumlahTercapai  int64  `json:"jumlah_tercapai"`
	TanggalTercapai string `json:"tanggal_tercapai"`
}

func (q *Queries) GetRekapSkpTercapaiByUser(ctx context.Context, arg GetRekapSkpTercapaiByUserParams) ([]GetRekapSkpTercapaiByUserRow, error) {
	rows, err := q.db.Query(ctx, getRekapSkpTercapaiByUser, arg.UserID, arg.TglAwal, arg.TglAkhir)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRekapSkpTercapaiByUserRow{}
	for rows.Next() {
		var i GetRekapSkpTercapaiByUserRow
		if err := rows.Scan(&i.NamaSkp, &i.JumlahTercapai, &i.TanggalTercapai); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const intervensiKehadiranID = `-- name: IntervensiKehadiranID :many
SELECT
ks.id,
  si.nama, 
  ks.skp_intervensi_id,
  ks.locked
FROM public.kehadiran_skp ks
LEFT JOIN public.skp_intervensi si
  ON ks.skp_intervensi_id = si.id
WHERE 
  ks.kehadiran_id = $1
  AND ks.is_active = TRUE
  AND ks.deleted_at IS NULL
ORDER BY ks.created_at DESC
`

type IntervensiKehadiranIDRow struct {
	ID              uuid.UUID `json:"id"`
	Nama            *string   `json:"nama"`
	SkpIntervensiID uuid.UUID `json:"skp_intervensi_id"`
	Locked          *bool     `json:"locked"`
}

func (q *Queries) IntervensiKehadiranID(ctx context.Context, kehadiranID uuid.UUID) ([]IntervensiKehadiranIDRow, error) {
	rows, err := q.db.Query(ctx, intervensiKehadiranID, kehadiranID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntervensiKehadiranIDRow{}
	for rows.Next() {
		var i IntervensiKehadiranIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.SkpIntervensiID,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKehadiranSkp = `-- name: ListKehadiranSkp :many
SELECT
  id,
  kehadiran_id,
  skp_intervensi_id,
  status,
  is_active,
  created_by,
  created_at
FROM kehadiran_skp
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status ILIKE '%' || $1 || '%')
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
  AND ($3::uuid IS NULL OR kehadiran_id = $3::uuid)
  AND ($4::uuid IS NULL OR skp_intervensi_id = $4::uuid)
ORDER BY
  CASE WHEN $5::text = 'status' AND $6::text = 'asc'  THEN status END ASC,
  CASE WHEN $5::text = 'status' AND $6::text = 'desc' THEN status END DESC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'asc'  THEN created_at END ASC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'desc' THEN created_at END DESC
LIMIT $8
OFFSET $7
`

type ListKehadiranSkpParams struct {
	Status          *string    `json:"status"`
	IsActive        *bool      `json:"is_active"`
	KehadiranID     *uuid.UUID `json:"kehadiran_id"`
	SkpIntervensiID *uuid.UUID `json:"skp_intervensi_id"`
	OrderBy         *string    `json:"order_by"`
	Sort            *string    `json:"sort"`
	Offset          int32      `json:"offset"`
	Limit           int32      `json:"limit"`
}

type ListKehadiranSkpRow struct {
	ID              uuid.UUID          `json:"id"`
	KehadiranID     uuid.UUID          `json:"kehadiran_id"`
	SkpIntervensiID uuid.UUID          `json:"skp_intervensi_id"`
	Status          *string            `json:"status"`
	IsActive        bool               `json:"is_active"`
	CreatedBy       *string            `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListKehadiranSkp(ctx context.Context, arg ListKehadiranSkpParams) ([]ListKehadiranSkpRow, error) {
	rows, err := q.db.Query(ctx, listKehadiranSkp,
		arg.Status,
		arg.IsActive,
		arg.KehadiranID,
		arg.SkpIntervensiID,
		arg.OrderBy,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKehadiranSkpRow{}
	for rows.Next() {
		var i ListKehadiranSkpRow
		if err := rows.Scan(
			&i.ID,
			&i.KehadiranID,
			&i.SkpIntervensiID,
			&i.Status,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skpKehadiranID = `-- name: SkpKehadiranID :many
SELECT skp_intervensi_id
FROM kehadiran_skp
WHERE kehadiran_id = $1
  AND is_active = true
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) SkpKehadiranID(ctx context.Context, kehadiranID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, skpKehadiranID, kehadiranID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var skp_intervensi_id uuid.UUID
		if err := rows.Scan(&skp_intervensi_id); err != nil {
			return nil, err
		}
		items = append(items, skp_intervensi_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncKehadiranSkp = `-- name: SyncKehadiranSkp :many
WITH
input_data AS (
    SELECT 
        unnest($1::uuid[]) AS skp_intervensi_id,
        $2::uuid AS kehadiran_id,
        $3::uuid AS user_id,
        $4::varchar AS actor
),

inserted AS (
    INSERT INTO kehadiran_skp (
        kehadiran_id,
        skp_intervensi_id,
        user_id,
        created_by
    )
    SELECT 
        i.kehadiran_id,
        i.skp_intervensi_id,
        i.user_id,
        i.actor
    FROM input_data i
    LEFT JOIN kehadiran_skp k
      ON k.kehadiran_id = i.kehadiran_id 
     AND k.skp_intervensi_id = i.skp_intervensi_id
    WHERE k.id IS NULL                 -- belum ada baris
       OR k.locked = false             -- atau baris belum terkunci
    ON CONFLICT (kehadiran_id, skp_intervensi_id)
    DO NOTHING
    RETURNING kehadiran_skp.id, kehadiran_skp.kehadiran_id, kehadiran_skp.skp_intervensi_id, kehadiran_skp.user_id, kehadiran_skp.status, kehadiran_skp.is_active, kehadiran_skp.locked, kehadiran_skp.deleted_by, kehadiran_skp.deleted_at, kehadiran_skp.updated_note, kehadiran_skp.updated_by, kehadiran_skp.updated_at, kehadiran_skp.created_by, kehadiran_skp.created_at
),

deleted AS (
    DELETE FROM kehadiran_skp k
    WHERE k.kehadiran_id = $2
      AND k.locked = false
      AND k.skp_intervensi_id NOT IN (SELECT skp_intervensi_id FROM input_data)
    RETURNING k.id, k.kehadiran_id, k.skp_intervensi_id, k.user_id, k.status, k.is_active, k.locked, k.deleted_by, k.deleted_at, k.updated_note, k.updated_by, k.updated_at, k.created_by, k.created_at
)

SELECT id, kehadiran_id, skp_intervensi_id, user_id, status, is_active, locked, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at FROM inserted
UNION ALL
SELECT id, kehadiran_id, skp_intervensi_id, user_id, status, is_active, locked, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at FROM deleted
`

type SyncKehadiranSkpParams struct {
	SkpIntervensiIds []uuid.UUID `json:"skp_intervensi_ids"`
	KehadiranID      uuid.UUID   `json:"kehadiran_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Actor            string      `json:"actor"`
}

type SyncKehadiranSkpRow struct {
	ID              uuid.UUID          `json:"id"`
	KehadiranID     uuid.UUID          `json:"kehadiran_id"`
	SkpIntervensiID uuid.UUID          `json:"skp_intervensi_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Status          *string            `json:"status"`
	IsActive        bool               `json:"is_active"`
	Locked          *bool              `json:"locked"`
	DeletedBy       *string            `json:"deleted_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote     *string            `json:"updated_note"`
	UpdatedBy       *string            `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       *string            `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// 1️⃣ Data input user
// 2️⃣ Insert baru hanya jika:
//   - baris belum ada, atau
//   - belum locked
//
// 3️⃣ Hapus baris yang:
//   - tidak ada di input user
//   - tidak locked
//
// 4️⃣ Gabungkan hasil operasi insert + delete
func (q *Queries) SyncKehadiranSkp(ctx context.Context, arg SyncKehadiranSkpParams) ([]SyncKehadiranSkpRow, error) {
	rows, err := q.db.Query(ctx, syncKehadiranSkp,
		arg.SkpIntervensiIds,
		arg.KehadiranID,
		arg.UserID,
		arg.Actor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncKehadiranSkpRow{}
	for rows.Next() {
		var i SyncKehadiranSkpRow
		if err := rows.Scan(
			&i.ID,
			&i.KehadiranID,
			&i.SkpIntervensiID,
			&i.UserID,
			&i.Status,
			&i.IsActive,
			&i.Locked,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.UpdatedNote,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKehadiranSkp = `-- name: UpdateKehadiranSkp :one
UPDATE kehadiran_skp
SET
  status       = COALESCE($1, status),
  is_active    = COALESCE($2, is_active),
  updated_by   = COALESCE($3, updated_by),
  updated_note = COALESCE($4, updated_note),
  updated_at   = now()
WHERE id = $5
  AND deleted_at IS NULL
RETURNING id, kehadiran_id, skp_intervensi_id, user_id, status, is_active, locked, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at
`

type UpdateKehadiranSkpParams struct {
	Status      *string   `json:"status"`
	IsActive    *bool     `json:"is_active"`
	UpdatedBy   *string   `json:"updated_by"`
	UpdatedNote *string   `json:"updated_note"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateKehadiranSkp(ctx context.Context, arg UpdateKehadiranSkpParams) (KehadiranSkp, error) {
	row := q.db.QueryRow(ctx, updateKehadiranSkp,
		arg.Status,
		arg.IsActive,
		arg.UpdatedBy,
		arg.UpdatedNote,
		arg.ID,
	)
	var i KehadiranSkp
	err := row.Scan(
		&i.ID,
		&i.KehadiranID,
		&i.SkpIntervensiID,
		&i.UserID,
		&i.Status,
		&i.IsActive,
		&i.Locked,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.UpdatedNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
