// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 11_r5_group_roles.sql

package pg

import (
	"context"
)

const createGroupRole = `-- name: CreateGroupRole :one
INSERT INTO r7_group_roles (
  group_id,
  role_id,
  created_by
) VALUES (
  $1, $2, $3
)
RETURNING id, group_id, role_id, is_active, deleted_by, deleted_at, updated_by, updated_at, created_by, created_at
`

type CreateGroupRoleParams struct {
	GroupID   int32   `json:"group_id"`
	RoleID    int32   `json:"role_id"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateGroupRole(ctx context.Context, arg CreateGroupRoleParams) (R7GroupRole, error) {
	row := q.db.QueryRow(ctx, createGroupRole, arg.GroupID, arg.RoleID, arg.CreatedBy)
	var i R7GroupRole
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RoleID,
		&i.IsActive,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
