// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 17_pembimbing_klinik.sql

package pg

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

const createPembimbingKlinik = `-- name: CreatePembimbingKlinik :one
INSERT INTO pembimbing_klinik (
    fasilitas_id, kontrak_id,user_id, created_by
) VALUES ($1, $2, $3, $4)
RETURNING id, fasilitas_id, kontrak_id, user_id, is_active, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at
`

type CreatePembimbingKlinikParams struct {
	FasilitasID uuid.UUID `json:"fasilitas_id"`
	KontrakID   uuid.UUID `json:"kontrak_id"`
	UserID      uuid.UUID `json:"user_id"`
	CreatedBy   *string   `json:"created_by"`
}

func (q *Queries) CreatePembimbingKlinik(ctx context.Context, arg CreatePembimbingKlinikParams) (PembimbingKlinik, error) {
	row := q.db.QueryRow(ctx, createPembimbingKlinik,
		arg.FasilitasID,
		arg.KontrakID,
		arg.UserID,
		arg.CreatedBy,
	)
	var i PembimbingKlinik
	err := row.Scan(
		&i.ID,
		&i.FasilitasID,
		&i.KontrakID,
		&i.UserID,
		&i.IsActive,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.UpdatedNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePembimbingKlinik = `-- name: DeletePembimbingKlinik :exec
DELETE FROM pembimbing_klinik
WHERE id = $1
`

func (q *Queries) DeletePembimbingKlinik(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePembimbingKlinik, id)
	return err
}

const getAllPembimbingKlinik = `-- name: GetAllPembimbingKlinik :many
SELECT id, fasilitas_id, kontrak_id, user_id, is_active, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at FROM pembimbing_klinik
ORDER BY created_at DESC
`

func (q *Queries) GetAllPembimbingKlinik(ctx context.Context) ([]PembimbingKlinik, error) {
	rows, err := q.db.Query(ctx, getAllPembimbingKlinik)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PembimbingKlinik{}
	for rows.Next() {
		var i PembimbingKlinik
		if err := rows.Scan(
			&i.ID,
			&i.FasilitasID,
			&i.KontrakID,
			&i.UserID,
			&i.IsActive,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.UpdatedNote,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPembimbingKlinikByID = `-- name: GetPembimbingKlinikByID :one
SELECT id, fasilitas_id, kontrak_id, user_id, is_active, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at FROM pembimbing_klinik
WHERE id = $1
`

func (q *Queries) GetPembimbingKlinikByID(ctx context.Context, id uuid.UUID) (PembimbingKlinik, error) {
	row := q.db.QueryRow(ctx, getPembimbingKlinikByID, id)
	var i PembimbingKlinik
	err := row.Scan(
		&i.ID,
		&i.FasilitasID,
		&i.KontrakID,
		&i.UserID,
		&i.IsActive,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.UpdatedNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPembimbingKlinikByKontrakID = `-- name: ListPembimbingKlinikByKontrakID :many
SELECT
    t2.id,
    t2.nama,
    t1.is_active
FROM
    pembimbing_klinik t1
JOIN
    users t2 ON t1.user_id = t2.id
WHERE
    t1.kontrak_id = $1
    AND t1.deleted_at IS NULL
`

type ListPembimbingKlinikByKontrakIDRow struct {
	ID       uuid.UUID `json:"id"`
	Nama     string    `json:"nama"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) ListPembimbingKlinikByKontrakID(ctx context.Context, kontrakID uuid.UUID) ([]ListPembimbingKlinikByKontrakIDRow, error) {
	rows, err := q.db.Query(ctx, listPembimbingKlinikByKontrakID, kontrakID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPembimbingKlinikByKontrakIDRow{}
	for rows.Next() {
		var i ListPembimbingKlinikByKontrakIDRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePembimbingKlinikPartial = `-- name: UpdatePembimbingKlinikPartial :one
UPDATE pembimbing_klinik
SET
  fasilitas_id = COALESCE($2, fasilitas_id),
  kontrak_id   = COALESCE($3, kontrak_id),
  user_id      = COALESCE($4, user_id),
  is_active    = COALESCE($5, is_active),
  updated_by   = COALESCE($6, updated_by),
  updated_note = COALESCE($7, updated_note),
  updated_at   = now()
WHERE id = $1
RETURNING id, fasilitas_id, kontrak_id, user_id, is_active, deleted_by, deleted_at, updated_note, updated_by, updated_at, created_by, created_at
`

type UpdatePembimbingKlinikPartialParams struct {
	ID          uuid.UUID  `json:"id"`
	FasilitasID *uuid.UUID `json:"fasilitas_id"`
	KontrakID   *uuid.UUID `json:"kontrak_id"`
	UserID      *uuid.UUID `json:"user_id"`
	IsActive    *bool      `json:"is_active"`
	UpdatedBy   *string    `json:"updated_by"`
	UpdatedNote *string    `json:"updated_note"`
}

func (q *Queries) UpdatePembimbingKlinikPartial(ctx context.Context, arg UpdatePembimbingKlinikPartialParams) (PembimbingKlinik, error) {
	row := q.db.QueryRow(ctx, updatePembimbingKlinikPartial,
		arg.ID,
		arg.FasilitasID,
		arg.KontrakID,
		arg.UserID,
		arg.IsActive,
		arg.UpdatedBy,
		arg.UpdatedNote,
	)
	var i PembimbingKlinik
	err := row.Scan(
		&i.ID,
		&i.FasilitasID,
		&i.KontrakID,
		&i.UserID,
		&i.IsActive,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.UpdatedNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
