// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"net/netip"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type FasilitasKesehatan struct {
	ID            uuid.UUID          `json:"id"`
	Nama          string             `json:"nama"`
	Propinsi      *string            `json:"propinsi"`
	Kab           *string            `json:"kab"`
	Alamat        *string            `json:"alamat"`
	Thumbnail     *string            `json:"thumbnail"`
	Telepon       *string            `json:"telepon"`
	Pemilik       *string            `json:"pemilik"`
	Kelas         *string            `json:"kelas"`
	Longitude     *float64           `json:"longitude"`
	Latitude      *float64           `json:"latitude"`
	GmapName      *string            `json:"gmap_name"`
	GmapAddress   *string            `json:"gmap_address"`
	GmapThumbnail *string            `json:"gmap_thumbnail"`
	Similarity    *int32             `json:"similarity"`
	Tipe          *string            `json:"tipe"`
	IsActive      bool               `json:"is_active"`
	DeletedBy     *string            `json:"deleted_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote   *string            `json:"updated_note"`
	UpdatedBy     *string            `json:"updated_by"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     *string            `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Kehadiran struct {
	ID           uuid.UUID          `json:"id"`
	FasilitasID  uuid.UUID          `json:"fasilitas_id"`
	KontrakID    uuid.UUID          `json:"kontrak_id"`
	RuanganID    string             `json:"ruangan_id"`
	PembimbingID uuid.UUID          `json:"pembimbing_id"`
	JadwalDinas  *string            `json:"jadwal_dinas"`
	UserID       uuid.UUID          `json:"user_id"`
	IsActive     bool               `json:"is_active"`
	DeletedBy    *string            `json:"deleted_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote  *string            `json:"updated_note"`
	UpdatedBy    *string            `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    *string            `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type KehadiranSkp struct {
	ID              uuid.UUID          `json:"id"`
	KehadiranID     uuid.UUID          `json:"kehadiran_id"`
	SkpIntervensiID uuid.UUID          `json:"skp_intervensi_id"`
	Status          *string            `json:"status"`
	IsActive        bool               `json:"is_active"`
	DeletedBy       *string            `json:"deleted_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote     *string            `json:"updated_note"`
	UpdatedBy       *string            `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       *string            `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Kontrak struct {
	ID             uuid.UUID          `json:"id"`
	FasilitasID    uuid.UUID          `json:"fasilitas_id"`
	Nama           string             `json:"nama"`
	PeriodeMulai   pgtype.Timestamptz `json:"periode_mulai"`
	PeriodeSelesai pgtype.Timestamptz `json:"periode_selesai"`
	Durasi         pgtype.Interval    `json:"durasi"`
	Deskripsi      *string            `json:"deskripsi"`
	IsActive       bool               `json:"is_active"`
	DeletedBy      *string            `json:"deleted_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote    *string            `json:"updated_note"`
	UpdatedBy      *string            `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      *string            `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MataKuliah struct {
	ID          uuid.UUID          `json:"id"`
	MataKuliah  string             `json:"mata_kuliah"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type R1Permission struct {
	ID        uuid.UUID          `json:"id"`
	Label     string             `json:"label"`
	Level     *int16             `json:"level"`
	ParentID  *string            `json:"parent_id"`
	Route     *string            `json:"route"`
	Method    *string            `json:"method"`
	Type      *string            `json:"type"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type R2GroupPermission struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type R3PermissionStatus struct {
	ID           uuid.UUID          `json:"id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	GroupID      uuid.UUID          `json:"group_id"`
	Value        *bool              `json:"value"`
	DeletedBy    *string            `json:"deleted_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy    *string            `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    *string            `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type R4UserRole struct {
	ID        uuid.UUID          `json:"id"`
	Tag       string             `json:"tag"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type R5PermissionRole struct {
	ID           uuid.UUID          `json:"id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	UserRolesID  uuid.UUID          `json:"user_roles_id"`
	IsActive     bool               `json:"is_active"`
	DeletedBy    *string            `json:"deleted_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy    *string            `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    *string            `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Ruangan struct {
	ID          uuid.UUID          `json:"id"`
	FasilitasID uuid.UUID          `json:"fasilitas_id"`
	KontrakID   uuid.UUID          `json:"kontrak_id"`
	NamaRuangan string             `json:"nama_ruangan"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SkpIntervensi struct {
	ID            uuid.UUID `json:"id"`
	KategoriID    uuid.UUID `json:"kategori_id"`
	SubkategoriID uuid.UUID `json:"subkategori_id"`
	Nama          string    `json:"nama"`
}

type SkpKategori struct {
	ID   uuid.UUID `json:"id"`
	Nama string    `json:"nama"`
}

type SkpSubkategori struct {
	ID         uuid.UUID `json:"id"`
	KategoriID uuid.UUID `json:"kategori_id"`
	Nama       string    `json:"nama"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Nama           string             `json:"nama"`
	Username       string             `json:"username"`
	Password       string             `json:"password"`
	Role           uuid.UUID          `json:"role"`
	LastActive     pgtype.Timestamptz `json:"last_active"`
	IsActive       bool               `json:"is_active"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	FailedAttempts *int32             `json:"failed_attempts"`
	LastFailedAt   pgtype.Timestamptz `json:"last_failed_at"`
	Refresh        *string            `json:"refresh"`
	DeletedBy      *string            `json:"deleted_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote    *string            `json:"updated_note"`
	UpdatedBy      *string            `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      *string            `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserGroup struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	GrupID    *string            `json:"grup_id"`
	Tipe      *string            `json:"tipe"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserLog struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	EntityName  string           `json:"entity_name"`
	EntityID    *uuid.UUID       `json:"entity_id"`
	Action      string           `json:"action"`
	Description *string          `json:"description"`
	IpAddress   *netip.Addr      `json:"ip_address"`
	UserAgent   *string          `json:"user_agent"`
	Device      *string          `json:"device"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Meta        []byte           `json:"meta"`
	Username    *string          `json:"username"`
}
