// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"net/netip"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type FasilitasKesehatan struct {
	ID            uuid.UUID          `json:"id"`
	Nama          string             `json:"nama"`
	Propinsi      *string            `json:"propinsi"`
	PropinsiID    *uuid.UUID         `json:"propinsi_id"`
	Kab           *string            `json:"kab"`
	KabID         *uuid.UUID         `json:"kab_id"`
	Alamat        *string            `json:"alamat"`
	Thumbnail     *string            `json:"thumbnail"`
	Telepon       *string            `json:"telepon"`
	Pemilik       *string            `json:"pemilik"`
	Kelas         *string            `json:"kelas"`
	Longitude     *float64           `json:"longitude"`
	Latitude      *float64           `json:"latitude"`
	GmapName      *string            `json:"gmap_name"`
	GmapAddress   *string            `json:"gmap_address"`
	GmapThumbnail *string            `json:"gmap_thumbnail"`
	Similarity    *int32             `json:"similarity"`
	Tipe          *string            `json:"tipe"`
	IsActive      bool               `json:"is_active"`
	DeletedBy     *string            `json:"deleted_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote   *string            `json:"updated_note"`
	UpdatedBy     *string            `json:"updated_by"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     *string            `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Kabupaten struct {
	ID          uuid.UUID          `json:"id"`
	Nama        string             `json:"nama"`
	PropinsiID  *uuid.UUID         `json:"propinsi_id"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Kehadiran struct {
	ID           uuid.UUID          `json:"id"`
	FasilitasID  uuid.UUID          `json:"fasilitas_id"`
	KontrakID    uuid.UUID          `json:"kontrak_id"`
	RuanganID    uuid.UUID          `json:"ruangan_id"`
	MataKuliahID uuid.UUID          `json:"mata_kuliah_id"`
	PembimbingID uuid.UUID          `json:"pembimbing_id"`
	JadwalDinas  *string            `json:"jadwal_dinas"`
	UserID       uuid.UUID          `json:"user_id"`
	IsActive     bool               `json:"is_active"`
	DeletedBy    *string            `json:"deleted_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote  *string            `json:"updated_note"`
	UpdatedBy    *string            `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TglKehadiran pgtype.Date        `json:"tgl_kehadiran"`
	Presensi     string             `json:"presensi"`
	CreatedBy    *string            `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type KehadiranSkp struct {
	ID              uuid.UUID          `json:"id"`
	KehadiranID     uuid.UUID          `json:"kehadiran_id"`
	SkpIntervensiID uuid.UUID          `json:"skp_intervensi_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Status          *string            `json:"status"`
	IsActive        bool               `json:"is_active"`
	DeletedBy       *string            `json:"deleted_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote     *string            `json:"updated_note"`
	UpdatedBy       *string            `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       *string            `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Kontrak struct {
	ID             uuid.UUID          `json:"id"`
	FasilitasID    uuid.UUID          `json:"fasilitas_id"`
	NoUtama        string             `json:"no_utama"`
	NoRef          string             `json:"no_ref"`
	PeriodeMulai   pgtype.Timestamptz `json:"periode_mulai"`
	PeriodeSelesai pgtype.Timestamptz `json:"periode_selesai"`
	Durasi         pgtype.Interval    `json:"durasi"`
	Deskripsi      *string            `json:"deskripsi"`
	IsActive       bool               `json:"is_active"`
	DeletedBy      *string            `json:"deleted_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote    *string            `json:"updated_note"`
	UpdatedBy      *string            `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      *string            `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MataKuliah struct {
	ID          uuid.UUID          `json:"id"`
	MataKuliah  string             `json:"mata_kuliah"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PembimbingKlinik struct {
	ID          uuid.UUID          `json:"id"`
	FasilitasID *uuid.UUID         `json:"fasilitas_id"`
	UserID      *uuid.UUID         `json:"user_id"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Propinsi struct {
	ID          uuid.UUID          `json:"id"`
	Nama        string             `json:"nama"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type R1View struct {
	ID          int32              `json:"id"`
	Label       string             `json:"label"`
	Level       *int16             `json:"level"`
	ParentID    *int32             `json:"parent_id"`
	Path        *string            `json:"path"`
	Method      *string            `json:"method"`
	ResourceKey string             `json:"resource_key"`
	Action      string             `json:"action"`
	View        *string            `json:"view"`
	Data        *string            `json:"data"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type R2Group struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type R3ViewRole struct {
	ID        uuid.UUID          `json:"id"`
	ViewID    int32              `json:"view_id"`
	RoleID    int32              `json:"role_id"`
	Action    *string            `json:"action"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type R4Role struct {
	ID        int32              `json:"id"`
	Tag       string             `json:"tag"`
	Nama      string             `json:"nama"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type R5UserRole struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	RoleID    int32              `json:"role_id"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type R6UserGroup struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	GrupID    int32              `json:"grup_id"`
	Tipe      *string            `json:"tipe"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type R7GroupRole struct {
	ID        uuid.UUID          `json:"id"`
	GroupID   int32              `json:"group_id"`
	RoleID    int32              `json:"role_id"`
	IsActive  bool               `json:"is_active"`
	DeletedBy *string            `json:"deleted_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedBy *string            `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Ruangan struct {
	ID          uuid.UUID          `json:"id"`
	FasilitasID uuid.UUID          `json:"fasilitas_id"`
	KontrakID   uuid.UUID          `json:"kontrak_id"`
	NamaRuangan string             `json:"nama_ruangan"`
	IsActive    bool               `json:"is_active"`
	DeletedBy   *string            `json:"deleted_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote *string            `json:"updated_note"`
	UpdatedBy   *string            `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SkpIntervensi struct {
	ID            uuid.UUID `json:"id"`
	KategoriID    uuid.UUID `json:"kategori_id"`
	SubkategoriID uuid.UUID `json:"subkategori_id"`
	Nama          string    `json:"nama"`
}

type SkpKategori struct {
	ID   uuid.UUID `json:"id"`
	Nama string    `json:"nama"`
}

type SkpSubkategori struct {
	ID         uuid.UUID `json:"id"`
	KategoriID uuid.UUID `json:"kategori_id"`
	Nama       string    `json:"nama"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Nama           string             `json:"nama"`
	Username       string             `json:"username"`
	Password       string             `json:"password"`
	LastActive     pgtype.Timestamptz `json:"last_active"`
	IsActive       bool               `json:"is_active"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	FailedAttempts *int32             `json:"failed_attempts"`
	LastFailedAt   pgtype.Timestamptz `json:"last_failed_at"`
	Refresh        *string            `json:"refresh"`
	DeletedBy      *string            `json:"deleted_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UpdatedNote    *string            `json:"updated_note"`
	UpdatedBy      *string            `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      *string            `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserLog struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	EntityName  string           `json:"entity_name"`
	EntityID    *uuid.UUID       `json:"entity_id"`
	Action      string           `json:"action"`
	Description *string          `json:"description"`
	IpAddress   *netip.Addr      `json:"ip_address"`
	UserAgent   *string          `json:"user_agent"`
	Device      *string          `json:"device"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Meta        []byte           `json:"meta"`
	Username    *string          `json:"username"`
}
