CREATE TABLE IF NOT EXISTS fasilitas_kesehatan (
	id UUID PRIMARY KEY  DEFAULT uuidv7(),
	nama TEXT NOT NULL,
	propinsi TEXT,
	propinsi_id UUID,
	kab TEXT,
	kab_id UUID,
	alamat TEXT,
	thumbnail TEXT,
	telepon TEXT,
	pemilik TEXT,
	kelas VARCHAR,
	longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
	gmap_name TEXT,
	gmap_address TEXT,
    gmap_thumbnail TEXT,
	similarity INTEGER,
    tipe VARCHAR,
	is_active BOOLEAN NOT NULL DEFAULT true,
    deleted_by VARCHAR,
    deleted_at TIMESTAMPTZ,
    updated_note TEXT,
    updated_by VARCHAR,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR,
    created_at TIMESTAMPTZ DEFAULT now()
);